### ISSUE TITLE
mariadbStart broken if service was running before

### ISSUE THREAD

**Issue by lukaszachy** [beakerlib/database#3]
`mariadbStart ` always fails if service is already running. In this case following happens
1. Clean datadir (no -k specified)
2. calll to rlServiceStart stops mariadb.service becasue it is alrady running
3. mariadb writes to datadir (`ib_buffer_pool`)
4. rlServiceStart (from 2.) tries to start mariadb.service

Fail happens because  datadir contains file but not everything -> mariadb refuses to start.

**Comment by hegerj** [comment]
This a known, unfortunate issue. I will look into possible ways how to solve it.

**Comment by hegerj** [comment]
might be fixed by ab2833d

**Comment by hegerj** [comment]
No issue turned up so far, closing the ticket.
